### ISSUE TITLE
Vaadinator + Java 8 + Lambda

### ISSUE THREAD

**Issue by Santiago-x** [akquinet/vaadinator#17]
Hello,

as soon as I add lambda expressions to my code, I get the following error message:
<pre>
[ERROR] Failed to execute goal de.akquinet.engineering.vaadin.vaadinator:VaadinatorGenerator:0.10-SNAPSHOT:codegenerator (generate-sources) on project XXX: Fehler bei Generieren: Encountered " ">" "> "" at line 20, column 52.
[ERROR] Was expecting one of:
[ERROR] "boolean" ...
[ERROR] "byte" ...
[ERROR] "char" ...
[ERROR] "double" ...
[ERROR] "false" ...
[ERROR] "float" ...
[ERROR] "int" ...
[ERROR] "long" ...
[ERROR] "new" ...
[ERROR] "null" ...
[ERROR] "short" ...
[ERROR] "super" ...
[ERROR] "this" ...
[ERROR] "true" ...
[ERROR] "void" ...
[ERROR] <LONG_LITERAL> ...
[ERROR] <INTEGER_LITERAL> ...
[ERROR] <FLOATING_POINT_LITERAL> ...
[ERROR] <CHARACTER_LITERAL> ...
[ERROR] <STRING_LITERAL> ...
[ERROR] <IDENTIFIER> ...
[ERROR] "(" ...
[ERROR] "!" ...
[ERROR] "~" ...
[ERROR] "++" ...
[ERROR] "--" ...
[ERROR] "+" ...
[ERROR] "-" ...
[ERROR] -> [Help 1]
</pre>

**Comment by OliverDamm** [comment]
Hi,

thank You for reporting this issue. I'll take a look on it.

Oliver

**Comment by OliverDamm** [comment]
Hi,

in the fix for issue #15, we replaced the java parser to support Java 8. The commit (c394971) was pushed to just 3 days ago. Do you use this revision?

I can only reproduce you error, if i use a revision before that commit mentioned above.

Please give us some feedback, so we can close this issue or do further investigations.

Oliver

**Comment by Santiago-x** [comment]
Dear Oliver,

you are right! It is already fixed in the newest version. 
Thanks!

**Comment by OliverDamm** [comment]
Hi, thanks for feedback.
