### ISSUE TITLE
Code is builded twice

### ISSUE THREAD

**Issue by dve** [akquinet/vaadinator#28]
The maven plugin builds the complete code two times, in the ```generate-sources``` and ```generate-resources``` phase.

This takes twice as long time, creates twice as much log messages and leads to confusion if you add a code formatter plugin to the ```generate-sources``` phase and to code is not formatted, because its overridden by the ```generate-resources``` run.

**Comment by sebastianrothbucher** [comment]
I'll look in2 it - thanks for reporting!

**Comment by sebastianrothbucher** [comment]
that was a mean one - the parameter was not pulled as the @parameter was missing. should work now. Thanks 4 reporting!
