### ISSUE TITLE
persitence.xml is not created correct

### ISSUE THREAD

**Issue by dve** [akquinet/vaadinator#29]
The persitence-unit name is plain name of the maven artifact, but in generated UI class its the capitalized, camelCased java style name.

One of them should be changed.

**Comment by sebastianrothbucher** [comment]
I'll look in2 it - thanks for reporting!

**Comment by dve** [comment]
The problem exists, because the ```persitence.xml``` is in the archetype, and uses the maven property ```artifactId``` while the UI is generated and uses the property ```common.projectName``` which is the camel cased ```artifactId```

**Comment by sebastianrothbucher** [comment]
used the plain artifcat name in this one case which fixes it (hope so, that is). Thanks for reporting!
