### ISSUE TITLE
Move "add" out of ListView and ListPresenter

### ISSUE THREAD

**Issue by dve** [akquinet/vaadinator#32]
Right now the list view and presenter contains the logic to add a new entity, the button and the observer implementation. In some cases this is not wanted - e.g. if one wants to use the list presenter to just select an existing entity.
My suggestion is to separate the selection part into a SelectView and -Presenter and let the list part use it.
Maybe it would be even clearer if we rename the List stuff to CRUD?

**Comment by dve** [comment]
I started a branch for this: https://github.com/dve/vaadinator/tree/extractSelect

**Comment by sebastianrothbucher** [comment]
As it's only a link 2 the functionality, I'd go about it as follows: I'd hide in the view and throw an unsupported operation on the server

**Comment by dve** [comment]
This seems to be a working way if you just want to do it for some presenter/view pairs. My goal is to provide vaadin field components for each entiy. This would allow us to handle entities which are referenced by other enties, like we have it for enums right now.

I would feel bad about hiding functionality in the generated code.

**Comment by sebastianrothbucher** [comment]
You've kind of lost me (& it's certainly me) - but w/ the Vaadin meetup coming up: let's talk then...

**Comment by sebastianrothbucher** [comment]
now I got it - feel free 2 do a PR!

**Comment by dve** [comment]
I used the new SelectPresenter in the ListPresenter for Desktop templates. Could you take a look on it and give feedback (AddressbookExample Desktop).
If you agree with this way I will go on with touchkit.

**Comment by sebastianrothbucher** [comment]
I'd start presenting after adding the view -  but otherwise (from a quick look), it does indeed look plausible...

**Comment by dve** [comment]
Ok, but the general way, ListPresenter has a SelectPresenter and not is a SelectPresnert is ok for you? Because I was in doubt about using composition or inheritance

**Comment by sebastianrothbucher** [comment]
Hi Daniel, I think you've very good structure in terms of composition and context - I do feel comfortable with going ahead using composition...
