### ISSUE TITLE
Property<Bean> BeanListPresenter.getBeanSelection() exposes vaadin detail

### ISSUE THREAD

**Issue by dve** [akquinet/vaadinator#34]
The method ```Property<Bean> BeanListView.getBeanSelection()``` exposes the interface ```com.vaadin.data.Property<T>```, which is a vaadin detail, out of the view layer.
Since the only usage of it is calling ```getValue()``` in the presenter, I suggest changing the method to ```Bean BeanListView.getBeanSelection()```

**Comment by sebastianrothbucher** [comment]
lgtm

**Comment by dve** [comment]
is merged to main
