### ISSUE TITLE
Missing artifact

### ISSUE THREAD

**Issue by tstsogoo** [akquinet/vaadinator#4]
Missing artifact de.akquinet.engineering.vaadin.vaadinator:VaadinatorAnnotations:jar:0.10-SNAPSHOT
Missing artifact de.akquinet.engineering.vaadin.vaadinator:VaadinatorUtils:jar:0.10-SNAPSHOT

Failed to execute goal on project AddressbookExample: Could not resolve dependencies for project de.akquinet.engineering.vaadin.vaadinator:AddressbookExample:war:0.10-SNAPSHOT: The following artifacts could not be resolved: de.akquinet.engineering.vaadin.vaadinator:VaadinatorAnnotations:jar:0.10-SNAPSHOT, de.akquinet.engineering.vaadin.vaadinator:VaadinatorUtils:jar:0.10-SNAPSHOT: Failure to find de.akquinet.engineering.vaadin.vaadinator:VaadinatorAnnotations:jar:0.10-SNAPSHOT in http://maven.vaadin.com/vaadin-addons was cached in the local repository, resolution will not be reattempted until the update interval of vaadin-addons has elapsed or updates are forced -> [Help 1]

Eclipse Luna
windows 8 x64

**Comment by sebastianrothbucher** [comment]
Sorry für die sehr späte Antwort, ich hatte vor Weihnachten total vergessen, dass hier noch etwas offen war - tut mir Leid! Anyway: für das neu-Generieren das eclipse:eclipse weglassen (also nur mvn generate-resources) könnte das Thema lösen...
